"""
CreditX Ecosystem - Shared Python Libraries
Enterprise-grade utilities for all microservices
"""
from .core_cache import DragonflyCache, get_cache, cache_lifespan, CacheMetrics
from .core_database import DatabaseClient, get_database, database_lifespan, DatabaseMetrics
from .core_config import Settings, get_settings
from .core_logging import (
    setup_logging,
    get_logger,
    set_request_context,
    clear_request_context,
    log_execution_time,
    RequestLogger,
    request_id_var,
    tenant_id_var,
    user_id_var,
)
from .core_resilience import (
    RetryConfig,
    retry_async,
    retry_sync,
    with_timeout,
    Bulkhead,
    BulkheadConfig,
    FallbackChain,
    create_circuit_breaker,
    get_circuit_breaker,
    circuit_breaker_status,
    RetryableError,
    NonRetryableError,
)
from .core_events import (
    EventBus,
    Event,
    EventType,
    get_event_bus,
)
from .core_spacemail import (
    SpacemailClient,
    EmailMessage,
    EmailRecipient,
    EmailPriority,
    SendResult,
    NotificationTemplates,
    get_spacemail,
)
from .core_thunderbolt import (
    ThunderboltClient,
    SecureMessage,
    Channel,
    MessageType,
    ChannelType,
    get_thunderbolt,
)
from .core_fastvpn import (
    FastVPNClient,
    TunnelConfig,
    TunnelConnection,
    TunnelType,
    TunnelStatus,
    EncryptionLevel,
    AccessToken,
    get_fastvpn,
)
from .core_ai import (
    AIRouter,
    AIProvider,
    ModelCapability,
    ModelConfig,
    Message,
    CompletionResult,
    UsageMetrics,
    get_ai_router,
    quick_complete,
    AVAILABLE_MODELS,
)
from .core_agents import (
    AgentOrchestrator,
    BaseAgent,
    AgentConfig,
    AgentTask,
    AgentState,
    AgentType,
    RiskLevel,
    Face,
    Engine,
    AgentStatus,
    get_orchestrator,
    AGENT_REGISTRY,
)

__all__ = [
    "DragonflyCache",
    "get_cache",
    "cache_lifespan",
    "CacheMetrics",
    "DatabaseClient",
    "get_database",
    "database_lifespan",
    "DatabaseMetrics",
    "Settings",
    "get_settings",
    "setup_logging",
    "get_logger",
    "set_request_context",
    "clear_request_context",
    "log_execution_time",
    "RequestLogger",
    "request_id_var",
    "tenant_id_var",
    "user_id_var",
    "RetryConfig",
    "retry_async",
    "retry_sync",
    "with_timeout",
    "Bulkhead",
    "BulkheadConfig",
    "FallbackChain",
    "create_circuit_breaker",
    "get_circuit_breaker",
    "circuit_breaker_status",
    "RetryableError",
    "NonRetryableError",
    "EventBus",
    "Event",
    "EventType",
    "get_event_bus",
    "SpacemailClient",
    "EmailMessage",
    "EmailRecipient",
    "EmailPriority",
    "SendResult",
    "NotificationTemplates",
    "get_spacemail",
    "ThunderboltClient",
    "SecureMessage",
    "Channel",
    "MessageType",
    "ChannelType",
    "get_thunderbolt",
    "FastVPNClient",
    "TunnelConfig",
    "TunnelConnection",
    "TunnelType",
    "TunnelStatus",
    "EncryptionLevel",
    "AccessToken",
    "get_fastvpn",
    "AIRouter",
    "AIProvider",
    "ModelCapability",
    "ModelConfig",
    "Message",
    "CompletionResult",
    "UsageMetrics",
    "get_ai_router",
    "quick_complete",
    "AVAILABLE_MODELS",
    "AgentOrchestrator",
    "BaseAgent",
    "AgentConfig",
    "AgentTask",
    "AgentState",
    "AgentType",
    "RiskLevel",
    "Face",
    "Engine",
    "AgentStatus",
    "get_orchestrator",
    "AGENT_REGISTRY",
]

__version__ = "1.0.0"
